### ISSUE TITLE
Add content-based detection?

### ISSUE THREAD

**Issue by lnmx** [mirage/ocaml-magic-mime#6]
I started working on a feature for detecting MIME type from file content, based on the [MIME Sniffing](https://mimesniff.spec.whatwg.org/) spec (as seen in the [Go stdlib](http://golang.org/src/net/http/sniff.go)).

Does this fit in with magic-mime, or should it be a separate project?  My work-in-progress is [here](https://github.com/lnmx/ocaml-magic-mime/tree/detect).

**Comment by talex5** [comment]
Note: there is a much more complete set of MIME magic rules here: http://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/

As I understand it, the MIME sniffing spec is for backwards compatibility (i.e. documenting common browser hacks), and is probably only useful if you're writing a browser.

**Comment by dsheets** [comment]
I believe this functionality is in scope. See #5.

**Comment by lnmx** [comment]
Thanks for the input -- I missed the previous issues on this topic.

I will look into the freedesktop db, and see about emitting different subsets as suggested in #3.

**Comment by avsm** [comment]
Totally in scope, and would be very useful Len!

**Comment by dsheets** [comment]
It would also be great to find a solution to mirage/ocaml-cohttp#275.

**Comment by avsm** [comment]
Just reopening this in case you are still interested in merging the feature @lnxm -- see the v1.1.0 that is now modernised and ready for hacking :-)

your branch on https://github.com/mirage/ocaml-magic-mime/compare/master...lnmx:detect seems to be heading in the right direction. I'm also wondering about how to solve #12 and do utf-8 charset detection

**Comment by undu** [comment]
I've looked at content-based detection this weekend. The approach that lnmx took to hand-roll the detection seems too labor-intensive compared to writing a generator based on the magic files of the `file` command, these are generated by https://github.com/file/file/tree/master/magic/Magdir. (see `man magic`)

**Comment by dinosaure** [comment]
Should I start to talk about a project which is a re-implementation of `libmagic` but in full OCaml: https://github.com/mirage/conan

`ocaml-magic-mime` has currently some higher constraints than `file` or `libmagic` because we want to incorporate that in a MirageOS - so no file-system or seek operation as we need for such introspection. So I started `conan` as a proof of concept which takes your pointed database and try to recognize a file.

The project is experimental and we have some well-know problems (about optimization, etc.). But, in the mid-term (/cc @clecat), we have plan to improve it and release it to replace the old and well-done `ocaml-magic-mime` project - and be compatible with MirageOS!

**Comment by dinosaure** [comment]
`conan` was released so you should take a look on this project now :+1:. I can close this issue.
